variables:
  TARGET_BRANCH: production

stages:
  - promote
  - pdk
  - yaml-lint
  - markdown-lint
  - sourceclear

default:
  interruptible: true
  timeout: 30m

workflow:
  rules:
    - when: always

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
